---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

inputs:
  - name: bucc-ci
  - name: bucc

caches:
  - path: bosh-cache

outputs:
  - name: bosh-cache
  - name: bucc-state-out

params:
  VARS:
  ARGS:

run:
  path: bucc-ci/ci/tasks/bucc-offline/task
